# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  build:
    docker:
      - image: cimg/node:20.4
    steps:
      - checkout
      - run:
          name: Run npm install
          command: npm install
      - run:
          name: Run basic unit tests
          command: npm run test

workflows:
  main:
    jobs:
      - build
